version: 2

# Optionally build your docs in additional formats such as PDF and ePub
formats:
   - pdf
   - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .
      
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
